### ISSUE TITLE
What about using CF environment variables instead of changing the buildpack?

### ISSUE THREAD

**Issue by grenik** [sbarzaghialteaup/demo-node-rfc-cf#1]
From your [commits](https://github.com/AlteaUP/nodejs-buildpack/commits/master) to the custom CF buildpack that you are using in this sample, I can see that the only difference to the default CF node.js buildpack are these two environment variables: 
```sh
export LD_LIBRARY_PATH=/home/vcap/app/sap/nwrfcsdk/lib/
export SAPNWRFC_HOME=/home/vcap/app/sap/nwrfcsdk
```

How do you think, can one set them via CF user-provided environment variables?

CF CLI
```sh
cf set-env your-app SAPNWRFC_HOME /home/vcap/app/sap/nwrfcsdk
cf set-env your-app LD_LIBRARY_PATH /home/vcap/app/sap/nwrfcsdk/lib/
```

Deployment descriptor:
```yaml
applications:
  - name: demo-node-rfc
    disk_quota: 300MB
    memory: 60MB
    instances: 1
    random-route: true
    health-check-type: process
    stack: cflinuxfs3
    env:
      LD_LIBRARY_PATH: /home/vcap/app/sap/nwrfcsdk/lib/
      SAPNWRFC_HOME: /home/vcap/app/sap/nwrfcsdk
    buildpacks:
      - nodejs_buildpack
```

SAP Business Technology Platform Cockpit:
![image](https://user-images.githubusercontent.com/39084120/150766501-bfb6d9fd-7197-4631-8346-cac9977e0d41.png)
